# -*- mode: ruby -*-
# vi: set ft=ruby :

VM_BOX = ENV["VM_BOX"] || "debian/stretch64"
VM_RAM = ENV["VM_RAM"] || "1024"
VM_CPU = ENV["VM_CPU"] || "2"

### Debian Desktop Environments -> https://wiki.debian.org/DesktopEnvironment
tasks = %w(
  gnome
  kde
  cinnamon
  lxde
  lxqt
  mate
  xfce
)

Vagrant.configure("2") do |config|

  config.vm.box = VM_BOX
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider "libvirt" do |lv|
      lv.memory = VM_RAM
      lv.cpus = VM_CPU
      lv.graphics_type = "spice"
      lv.video_type = "qxl"
      lv.channel type: "spicevmc", target_name: "com.redhat.spice.0", target_type: "virtio"
      lv.channel type: "unix", target_name: "org.qemu.guest_agent.0", target_type: "virtio"
  end
  config.vm.provider "virtualbox" do |vb|
      vb.memory = VM_RAM
      vb.cpus = VM_CPU
  end

  tasks.each do |i|
    config.vm.define "debian-#{i}" do |vm|
      vm.vm.hostname = "debian-#{i}"
      vm.vm.provision "passwd", type: "shell", inline: %Q[echo -e "vagrant\nvagrant" | passwd vagrant]
      vm.vm.provision "update", type: "shell", inline: "apt-get update"
      vm.vm.provision i, type: "shell", inline: "DEBIAN_FRONTEND=noninteractive apt-get install -yq task-#{i}-desktop"
      vm.vm.provision "vdagent", type: "shell", inline: "apt-get install -yq spice-vdagent"
      vm.vm.provision "reboot", type: "shell", inline: "reboot"
    end
  end

end
